/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Event {
  'id' : string,
  'content' : string,
  'metadata' : string,
  'sender' : string,
  'timestamp' : Time,
  'threadId' : string,
  'eventType' : EventType,
}
export type EventType = { 'action' : null } |
  { 'text' : null } |
  { 'telegramMessage' : null };
export interface Thread {
  'id' : string,
  'title' : string,
  'participants' : Array<string>,
  'owner' : Principal,
  'timestamp_created' : Time,
  'timestamp_modified' : Time,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'telegramUsername' : [] | [string],
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEvent' : ActorMethod<[string, string, EventType, string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createThread' : ActorMethod<[string, Array<string>], string>,
  'deleteAll' : ActorMethod<[], undefined>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'deleteThread' : ActorMethod<[string], undefined>,
  'deleteThreadEvents' : ActorMethod<[string], undefined>,
  'getAllThreads' : ActorMethod<[], Array<Thread>>,
  'getAllThreadsWithEvents' : ActorMethod<[], Array<[Thread, Array<Event>]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvent' : ActorMethod<[string], [] | [Event]>,
  'getEventsByThread' : ActorMethod<[string], Array<Event>>,
  'getThread' : ActorMethod<[string], [] | [Thread]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'makeGetOutcall' : ActorMethod<[string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateThread' : ActorMethod<[string, string, Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];