/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EventType = IDL.Variant({
  'action' : IDL.Null,
  'text' : IDL.Null,
  'telegramMessage' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Thread = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'participants' : IDL.Vec(IDL.Text),
  'owner' : IDL.Principal,
  'timestamp_created' : Time,
  'timestamp_modified' : Time,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'metadata' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : Time,
  'threadId' : IDL.Text,
  'eventType' : EventType,
});
export const UserProfile = IDL.Record({
  'telegramUsername' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEvent' : IDL.Func(
      [IDL.Text, IDL.Text, EventType, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createThread' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Text], []),
  'deleteAll' : IDL.Func([], [], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'deleteThread' : IDL.Func([IDL.Text], [], []),
  'deleteThreadEvents' : IDL.Func([IDL.Text], [], []),
  'getAllThreads' : IDL.Func([], [IDL.Vec(Thread)], ['query']),
  'getAllThreadsWithEvents' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Thread, IDL.Vec(Event)))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvent' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
  'getEventsByThread' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
  'getThread' : IDL.Func([IDL.Text], [IDL.Opt(Thread)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'makeGetOutcall' : IDL.Func([IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateThread' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EventType = IDL.Variant({
    'action' : IDL.Null,
    'text' : IDL.Null,
    'telegramMessage' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Thread = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'participants' : IDL.Vec(IDL.Text),
    'owner' : IDL.Principal,
    'timestamp_created' : Time,
    'timestamp_modified' : Time,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'metadata' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : Time,
    'threadId' : IDL.Text,
    'eventType' : EventType,
  });
  const UserProfile = IDL.Record({
    'telegramUsername' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEvent' : IDL.Func(
        [IDL.Text, IDL.Text, EventType, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createThread' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Text], []),
    'deleteAll' : IDL.Func([], [], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'deleteThread' : IDL.Func([IDL.Text], [], []),
    'deleteThreadEvents' : IDL.Func([IDL.Text], [], []),
    'getAllThreads' : IDL.Func([], [IDL.Vec(Thread)], ['query']),
    'getAllThreadsWithEvents' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Thread, IDL.Vec(Event)))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvent' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
    'getEventsByThread' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
    'getThread' : IDL.Func([IDL.Text], [IDL.Opt(Thread)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'makeGetOutcall' : IDL.Func([IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateThread' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };